language: python
sudo: false
cache: pip
python:
  - 3.6
  - 3.5
  - 2.7
env:
  - DJANGO="2.0"
  - DJANGO="1.11"
matrix:
  fast_finish: true
  exclude:
    - env: DJANGO="2.0"
      python: 2.7
  include:
    - env: TOXENV=flake8,readme
      python: 3.6
install: pip install tox-travis
script: tox
